-- MistDocs schema for a fresh install (md_* tables only).
-- Generated by scripts/gen-init-db.sh from a migrated local database.
-- Accounts, teams and team members live in the Portal's users / teams /
-- team_members tables in the same database. For a local dev/demo install
-- without the Portal, also load docker/dev-portal-tables.sql.
SET NAMES utf8mb4;

-- table: md_documents
CREATE TABLE IF NOT EXISTS `md_documents` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) DEFAULT '',
  `folder_id` varchar(36) DEFAULT NULL,
  `department_id` varchar(36) NOT NULL DEFAULT '',
  `title` varchar(200) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'doc',
  `file_path` varchar(500) DEFAULT NULL,
  `file_size` bigint(20) DEFAULT 0,
  `version` int(11) DEFAULT 1,
  `locked_by` varchar(36) DEFAULT '',
  `locked_at` datetime DEFAULT NULL,
  `status` tinyint(4) DEFAULT 1,
  `created_by` varchar(36) DEFAULT NULL,
  `updated_by` varchar(36) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `content_text` longtext DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_folder` (`folder_id`),
  KEY `idx_dept` (`department_id`),
  KEY `idx_status` (`status`),
  KEY `idx_type` (`type`),
  KEY `idx_md_docs_team` (`team_id`),
  FULLTEXT KEY `ft_content_text` (`content_text`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_audits
CREATE TABLE IF NOT EXISTS `md_audits` (
  `id` varchar(36) NOT NULL,
  `user_id` varchar(36) NOT NULL,
  `user_name` varchar(100) DEFAULT NULL,
  `department_id` varchar(36) DEFAULT NULL,
  `action` varchar(30) NOT NULL,
  `resource_type` varchar(10) DEFAULT NULL,
  `resource_id` varchar(36) DEFAULT NULL,
  `resource_name` varchar(200) DEFAULT NULL,
  `detail` text DEFAULT NULL,
  `ip` varchar(50) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `team_id` varchar(64) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_dept` (`department_id`),
  KEY `idx_action` (`action`),
  KEY `idx_resource` (`resource_type`,`resource_id`),
  KEY `idx_time` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_comments
CREATE TABLE IF NOT EXISTS `md_comments` (
  `id` varchar(36) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `content` text NOT NULL,
  `parent_id` varchar(36) DEFAULT NULL,
  `user_id` varchar(36) NOT NULL,
  `user_name` varchar(100) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `team_id` varchar(64) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_comment_doc` (`document_id`),
  KEY `idx_comment_parent` (`parent_id`),
  KEY `idx_comment_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_deadlines
CREATE TABLE IF NOT EXISTS `md_deadlines` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `order_no` varchar(64) NOT NULL,
  `title` varchar(255) NOT NULL,
  `customer` varchar(128) DEFAULT '',
  `quantity` int(11) DEFAULT 0,
  `start_date` date DEFAULT NULL,
  `due_date` date NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'pending',
  `progress` tinyint(4) DEFAULT 0,
  `priority` varchar(16) NOT NULL DEFAULT 'normal',
  `owner_id` varchar(64) DEFAULT '',
  `remark` text DEFAULT NULL,
  `created_by` varchar(64) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_by` varchar(64) DEFAULT '',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `deleted_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_due` (`team_id`,`due_date`,`status`),
  KEY `idx_owner` (`team_id`,`owner_id`),
  KEY `idx_status` (`team_id`,`status`),
  KEY `idx_order` (`team_id`,`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_deadline_events
CREATE TABLE IF NOT EXISTS `md_deadline_events` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `deadline_id` varchar(36) NOT NULL,
  `event_type` varchar(32) NOT NULL COMMENT 'created|updated|status_changed|date_changed|deleted',
  `field` varchar(32) DEFAULT '',
  `old_value` text DEFAULT NULL,
  `new_value` text DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `actor_id` varchar(64) DEFAULT '',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_deadline` (`deadline_id`,`created_at`),
  KEY `idx_team` (`team_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_doc_fragments
CREATE TABLE IF NOT EXISTS `md_doc_fragments` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `fragment_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `position` int(11) NOT NULL DEFAULT 0,
  `created_by` varchar(64) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doc_frag` (`document_id`,`fragment_id`),
  KEY `idx_team` (`team_id`),
  KEY `idx_doc` (`document_id`),
  KEY `idx_frag` (`fragment_id`),
  CONSTRAINT `fk_docfrag_doc` FOREIGN KEY (`document_id`) REFERENCES `md_documents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_doc_tags
CREATE TABLE IF NOT EXISTS `md_doc_tags` (
  `id` varchar(36) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `tag_id` varchar(36) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doc_tag` (`document_id`,`tag_id`),
  KEY `idx_doc` (`document_id`),
  KEY `idx_tag` (`tag_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_favorites
CREATE TABLE IF NOT EXISTS `md_favorites` (
  `id` varchar(36) NOT NULL,
  `user_id` varchar(36) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_doc` (`user_id`,`document_id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_keys
CREATE TABLE IF NOT EXISTS `md_keys` (
  `id` varchar(36) NOT NULL,
  `type` varchar(10) NOT NULL COMMENT 'master/dek/kek',
  `status` varchar(10) NOT NULL DEFAULT 'active' COMMENT 'active/inactive/rotated',
  `encrypted` text NOT NULL COMMENT 'base64 encoded encrypted key material',
  `algorithm` varchar(20) NOT NULL DEFAULT 'AES-256-GCM',
  `created_at` datetime DEFAULT current_timestamp(),
  `rotated_from` varchar(36) DEFAULT NULL COMMENT 'previous key ID during rotation',
  `created_by` varchar(100) DEFAULT 'system',
  PRIMARY KEY (`id`),
  KEY `idx_type_status` (`type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_media
CREATE TABLE IF NOT EXISTS `md_media` (
  `filename` varchar(100) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `original_name` varchar(255) NOT NULL DEFAULT '',
  `uploaded_by` varchar(64) NOT NULL,
  `size` bigint(20) NOT NULL DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`team_id`,`filename`),
  KEY `idx_uploader` (`uploaded_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_notifications
CREATE TABLE IF NOT EXISTS `md_notifications` (
  `id` varchar(36) NOT NULL,
  `user_id` varchar(36) NOT NULL,
  `type` varchar(32) NOT NULL,
  `title` varchar(255) NOT NULL,
  `document_id` varchar(36) DEFAULT NULL,
  `related_id` varchar(36) DEFAULT NULL,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `team_id` varchar(64) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_notif_user` (`user_id`),
  KEY `idx_notif_read` (`user_id`,`is_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_permissions
CREATE TABLE IF NOT EXISTS `md_permissions` (
  `id` varchar(36) NOT NULL,
  `resource_type` varchar(10) NOT NULL,
  `resource_id` varchar(36) NOT NULL,
  `target_type` varchar(10) NOT NULL,
  `target_id` varchar(36) NOT NULL,
  `permission` varchar(10) NOT NULL DEFAULT 'read',
  `inherit` tinyint(4) DEFAULT 1,
  `created_by` varchar(36) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_perm` (`resource_type`,`resource_id`,`target_type`,`target_id`),
  KEY `idx_resource` (`resource_type`,`resource_id`),
  KEY `idx_target` (`target_type`,`target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_proposals
CREATE TABLE IF NOT EXISTS `md_proposals` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `user_id` varchar(64) NOT NULL,
  `kind` varchar(32) NOT NULL DEFAULT 'insert' COMMENT 'insert|date_change|explain',
  `title` varchar(255) NOT NULL DEFAULT '',
  `payload` longtext NOT NULL,
  `baseline` longtext NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'pending' COMMENT 'pending|applied|rejected|stale',
  `decided_by` varchar(64) DEFAULT '',
  `decided_at` datetime DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_team_time` (`team_id`,`created_at`),
  KEY `idx_team_status` (`team_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_reminder_log
CREATE TABLE IF NOT EXISTS `md_reminder_log` (
  `id` varchar(36) NOT NULL,
  `rule_id` varchar(36) NOT NULL,
  `deadline_id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `target_user_id` varchar(64) DEFAULT '',
  `channel` varchar(32) NOT NULL DEFAULT 'inapp',
  `result` varchar(16) NOT NULL DEFAULT 'ok',
  `detail` varchar(255) DEFAULT '',
  `sent_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_once` (`rule_id`,`deadline_id`),
  KEY `idx_deadline` (`deadline_id`),
  KEY `idx_team_time` (`team_id`,`sent_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_reminder_rules
CREATE TABLE IF NOT EXISTS `md_reminder_rules` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `name` varchar(64) NOT NULL,
  `offset_days` int(11) NOT NULL COMMENT 'days before due date; 0 = due today; negative = overdue',
  `channel` varchar(32) NOT NULL DEFAULT 'inapp' COMMENT 'inapp|webhook',
  `target` varchar(32) NOT NULL DEFAULT 'owner' COMMENT 'owner|creator',
  `enabled` tinyint(1) NOT NULL DEFAULT 1,
  `created_by` varchar(64) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_team` (`team_id`,`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_shares
CREATE TABLE IF NOT EXISTS `md_shares` (
  `id` varchar(36) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `token` varchar(64) NOT NULL,
  `password` varchar(100) DEFAULT '',
  `expires_at` datetime DEFAULT NULL,
  `created_by` varchar(36) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `access_count` int(11) NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `team_id` varchar(64) DEFAULT '',
  `permission` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `idx_share_doc` (`document_id`),
  KEY `idx_share_token` (`token`),
  KEY `idx_share_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_tags
CREATE TABLE IF NOT EXISTS `md_tags` (
  `id` varchar(36) NOT NULL,
  `name` varchar(50) NOT NULL,
  `color` varchar(7) DEFAULT '#409eff',
  `user_id` varchar(36) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `team_id` varchar(64) DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_tag` (`user_id`,`name`),
  KEY `idx_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_team_capacity
CREATE TABLE IF NOT EXISTS `md_team_capacity` (
  `team_id` varchar(64) NOT NULL,
  `effective_from` date NOT NULL,
  `per_day` int(11) NOT NULL DEFAULT 1,
  `key_customers` text DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT '',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`team_id`,`effective_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_team_folders
CREATE TABLE IF NOT EXISTS `md_team_folders` (
  `id` varchar(36) NOT NULL,
  `team_id` varchar(64) NOT NULL,
  `parent_id` varchar(36) DEFAULT '',
  `name` varchar(200) NOT NULL,
  `sort_order` int(11) DEFAULT 0,
  `created_by` varchar(64) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_team` (`team_id`),
  KEY `idx_parent` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_templates
CREATE TABLE IF NOT EXISTS `md_templates` (
  `id` varchar(36) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'doc',
  `content` longtext DEFAULT NULL,
  `user_id` varchar(36) NOT NULL,
  `department_id` varchar(36) DEFAULT '',
  `is_public` tinyint(1) DEFAULT 0,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `team_id` varchar(64) DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `idx_user` (`user_id`),
  KEY `idx_dept` (`department_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_versions
CREATE TABLE IF NOT EXISTS `md_versions` (
  `id` varchar(36) NOT NULL,
  `document_id` varchar(36) NOT NULL,
  `version` int(11) NOT NULL,
  `file_path` varchar(500) NOT NULL,
  `file_size` bigint(20) DEFAULT 0,
  `created_by` varchar(36) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_doc_version` (`document_id`,`version`),
  KEY `idx_doc` (`document_id`),
  CONSTRAINT `fk_md_version_doc` FOREIGN KEY (`document_id`) REFERENCES `md_documents` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_webhooks
CREATE TABLE IF NOT EXISTS `md_webhooks` (
  `id` varchar(36) NOT NULL,
  `name` varchar(100) NOT NULL,
  `url` varchar(500) NOT NULL,
  `secret` varchar(200) DEFAULT '',
  `events` varchar(500) DEFAULT 'create,update,delete',
  `created_by` varchar(36) DEFAULT '',
  `created_at` datetime DEFAULT current_timestamp(),
  `enabled` tinyint(1) DEFAULT 1,
  `team_id` varchar(64) DEFAULT '',
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

-- table: md_webhook_logs
CREATE TABLE IF NOT EXISTS `md_webhook_logs` (
  `id` varchar(36) NOT NULL,
  `webhook_id` varchar(36) NOT NULL,
  `event` varchar(50) NOT NULL,
  `status` varchar(200) DEFAULT '',
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_webhook` (`webhook_id`),
  KEY `idx_time` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
;

