#!/bin/bash
# gen-init-db.sh — regenerate docker/init-db.sql from a local database that
# the server has already migrated (for example the integration-test DB after
# a `go test ./tests/` run). Never point it at production.
#
#   scripts/gen-init-db.sh mistdocs_it > docker/init-db.sql
#
# Only md_* tables that current code uses are written. The legacy md_users,
# md_departments and md_folders tables (pre-Portal accounts and folders) are
# left out: fresh installs get accounts from the Portal and folders from
# md_team_folders. Tables the server creates on start (templates, team
# folders, deadlines, media...) are included too so the file is a complete
# picture; database.Migrate skips anything that exists.
set -euo pipefail
DB="${1:?用法: $0 <本地库名>}"
ROOT_CMD="${MYSQL_ROOT:-sudo mariadb}"
case "$DB" in *prod*|mist_team) echo "refusing '$DB'" >&2; exit 1;; esac

LEGACY="'md_users','md_departments','md_folders'"
# md_documents first: md_versions and md_doc_fragments reference it.
TABLES=$($ROOT_CMD -N "$DB" -e "SELECT TABLE_NAME FROM information_schema.TABLES
  WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME LIKE 'md\\_%' AND TABLE_NAME NOT IN ($LEGACY)
  ORDER BY TABLE_NAME<>'md_documents', TABLE_NAME")

echo "-- MistDocs schema for a fresh install (md_* tables only)."
echo "-- Generated by scripts/gen-init-db.sh from a migrated local database."
echo "-- Accounts, teams and team members live in the Portal's users / teams /"
echo "-- team_members tables in the same database. For a local dev/demo install"
echo "-- without the Portal, also load docker/dev-portal-tables.sql."
echo "SET NAMES utf8mb4;"
echo
for t in $TABLES; do
  echo "-- table: $t"
  $ROOT_CMD -N "$DB" -e "SHOW CREATE TABLE \`$t\`" | cut -f2- | sed -e 's/\\n/\n/g' \
    -e 's/^CREATE TABLE/CREATE TABLE IF NOT EXISTS/' -e 's/ AUTO_INCREMENT=[0-9]*//'
  echo ";"
  echo
done
